#!/usr/local/bin/python
# -*- coding: UTF-8 -*-

__VERSION__ = "0.0.3d"

import random, os, string, sys

art_info = {
    #Artist (short name),	Artist (long name),	Painting name,	Date painted, Notes
    "Alexander_StudyInBlackAndGreen.png": ['Alexander',	'John White Alexander',	'Study In Black And Green',	'1906', None],
    "Anshutz_ARose.png": ['Anshutz',	'Thomas Anshutz',	'A Rose',	'1907', None],
    "Boccioni_ForcesOfTheStreet.png": ['Boccioni',	'Umberto Boccioni',	'Forces Of The Street',	'1911', None],
    "Boccioni_StatesOfMindThoseWhoGo.png": ['Boccioni',	'Umberto Boccioni',	'States Of Mind: Those Who Go',	'1912', None],
    "Boccioni_YoungManOnRiverbank.png": ['Boccioni',	'Umberto Boccioni',	'Young Man On Riverbank',	'1902', None],
    "Bosch_TheGardenOfEarthlyDelights.png": ['Bosch',	'Hieronymus Bosch',	'The Garden Of Earthly Delights',	'1480', None],
    "Bruegel_TheHarvesters.png": ['Bruegel',	'Pieter Bruegel',	'The Harvesters',	'1565', None],
    "Bruegel_ThreeCaravelsInARisingSquall.png": ['Bruegel',	'Pieter Bruegel',	'Three Caravels In A Rising Squall',	'1561', None],
    "Brueghel_LandscapeWithTheFallOfIcarus.png": ['Brueghel',	'Pieter Brueghel',	'Landscape With The Fall Of Icarus',	'1558', None],
    "Brueghel_TheTowerOfBabel.png": ['Brueghel',	'Pieter Brueghel',	'The Tower Of Babel',	'1563', None],
    "BurneJones_TheLoveSong.png": ['Burne-Jones',	'Sir Edward Burne-Jones',	'The Love Song',	'1868', None],
    "Canaletto_PiazzaSanMarco.png": ['Canaletto',	'Canaletto',	'Piazza San Marco',	'1720', None],
    "Cezanne_BendInTheRoadThroughTheForest.png": ['Cezanne',	'Paul Cezanne',	'Bend In The Road Through The Forest',	'1873', None],
    "Cezanne_FourPeachesOnAPlate.png": ['Cezanne',	'Paul Cezanne',	'Four Peaches On A Plate',	'1890', None],
    "Cezanne_LandscapeNearParis.png": ['Cezanne',	'Paul Cezanne',	'Landscape Near Paris',	'1876', None],
    "Cezanne_PaysageDeLIleDeFrance.png": ['Cezanne',	'Paul Cezanne',	"Paysage de l'Ile-de-France",	'1880', None],
    "Cezanne_StillLifeWithApplesAndPotOfPrimroses.png": ['Cezanne',	'Paul Cezanne',	'Still Life With Apples And Pot Of Primroses',	'1890', None],
    "Cezanne_TheCardPlayers.png": ['Cezanne',	'Paul Cezanne',	'The Card Players',	'1890', None],
    "Cezanne_TreesAndHousesNearJasDeBouffan.png": ['Cezanne',	'Paul Cezanne',	'Trees And Houses Near Jas De Bouffan',	'1885', None],
    "Cezanne_MontSainteVictoire.png": ['Cezanne',	'Paul Cezanne',	'Mont Sainte Victoire',	'1902', None],
    "Cezanne_MontSainteVictoireWithLargePine.png": ['Cezanne',	'Paul Cezanne',	'Mont Sainte Victoire With Large Pine',	'1887', None],
    "Cezanne_-_Still_Life_With_Quince,_Apples,_and_Pear.png": ['Cezanne',	'Paul Cezanne',	'Still Life With Quince, Apples, and Pear',	'1885', None],
    "Cézanne_TheBasketOfApples.png": ['Cezanne',	'Paul Cezanne',	'The Basket Of Apples',	'1895', None],
    "Constable_CloudStudy.png": ['Constable',	'John Constable',	'Cloud Study',	'1830', None],
    "Constable_DedhamLockAndMill.png": ['Constable',	'John Constable',	'Dedham Lock And Mill',	'1820', None],
    "Constable_StokeByNayland.png": ['Constable',	'John Constable',	'Stoke By Nayland',	'1810', None],
    "Constable_TheHayWain.png": ['Constable',	'John Constable',	'The Hay Wain',	'1821', None],
    "Constable_TheOpeningOfWaterlooBridge.png": ['Constable',	'John Constable',	'The Opening Of Waterloo Bridge',	'1829', None],
    "Constable_TheWheatField.png": ['Constable',	'John Constable',	'The Wheat Field',	'1816', None],
    "Constable_HampsteadHeathWithARainbow.png": ['Constable',	'John Constable',	'Hampstead Heath with a Rainbow',	'1836', None],
    "Cot_Springtime.png": ['Cot',	'Pierre-Auguste Cot',	'Springtime',	'1873', None],
    "Cushing_MrsEthelCushing.png": ['Cushing',	'Howard Cushing',	'Mrs Ethel Cushing',	'1912', None],
    "Cuvelier_FontainebleauForest.png": ['Cuvelier',	'Eugene Cuvelier',	'Fontainebleau Forest',	'1860', None],
    "Degas_Dancer.png": ['Degas',	'Edgar Degas',	'Dancer',	'1880', None],
    "Degas_TheDanceClass.png": ['Degas',	'Edgar Degas',	'The Dance Class',	'1874', None],
    "Degas_TheDancers.png": ['Degas',	'Edgar Degas',	'The Dancers',	'1900', None],
    "Degas_TheSingerInGreen.png": ['Degas',	'Edgar Degas',	'The Singer In Green',	'1884', None],
    "Degas_WomanSeatedBesideVaseOfFlowers.png": ['Degas',	'Edgar Degas',	'Woman Seated Beside Vase Of Flowers',	'1865', None],
    "Degas_TwoDancersEnteringTheStage.png": ['Degas',	'Edgar Degas',	'Two Dancers Entering The Stage',	'1877', None],
    "Delacroix_ArtistsGardenAtSaintClair.png": ['Delacroix',	'Henri-Edmond Delacroix',	'Artists Garden At Saint Clair',	'1904', None],
    "Delacroix_LandscapeWithStars.png": ['Delacroix',	'Henri-Edmond Delacroix',	'Landscape With Stars',	'1905', None],
    "Delacroix_ValleyWithFir.png": ['Delacroix',	'Henri-Edmond Delacroix',	'Valley With Fir',	'1909', None],
    "Diulgheroff_LEquilibreSpirituel.png": ['Diulgheroff',	'Nikolay Diulgheroff',	"L'equilibre Spirituel",	'1923', None],
    "Diulgheroff_LeMarin.png": ['Diulgheroff',	'Nikolay Diulgheroff',	'Le Marin',	'1930', None],
    "Diulgheroff_RationalMan.png": ['Diulgheroff',	'Nikolay Diulgheroff',	'Rational Man',	'1928', None],
    "Donoho_Windflowers.png": ['Donoho',	'Ruger Donoho',	'Windflowers',	'1912', None],
    "Durand_TheBeeches.png": ['Durand',	'Asher Brown Durand',	'The Beeches',	'1845', None],
    "Eakins_TwoPupilsInGreekDress.png": ['Eakins',	'Thomas Eakins',	'Two Pupils In Greek Dress',	'1883', None],
    "FantinLatour_Pansies.png": ['Fantin-Latour',	'Henri Fantin-Latour',	'Pansies',	'1903', None],
    "Gauguin_IaOranaMaria.png": ['Gauguin',	'Paul Gauguin',	'Ia Orana Maria',	'1891', None],
    "Gauguin_TwoWomen.png": ['Gauguin',	'Paul Gauguin',	'Two Women',	'1901', None],
    "Gericault_TheRaftOfTheMedusa.png": ['Gericault',	'Theodore Gericault',	'The Raft Of The Medusa',	'1818', None],
    "Gerome_BashiBazouk.png": ['Gerome',	'Jean-Léon Gérome',	'Bashi Bazouk',	'1868', None],
    "Goya_StillLifeWithFruitBottlesBread.png": ['Goya',	'Francisco Goya',	'Still Life With Fruit, Bottles, Bread',	'1824', None],
    "Goya_TheClothedMaja.png": ['Goya',	'Francisco Goya',	'The Clothed Maja',	'1800', None],
    "Goya_TheParasol.png": ['Goya',	'Francisco Goya',	'The Parasol',	'1777', None],
    "Gris_StillLifeWithCheckedTablecloth.png": ['Gris',	'Juan Gris',	'Still Life With Checked Tablecloth',	'1913', None],
    "Harper_TreesEarlyAfternoonFrance.png": ['Harper',	'William A. Harper',	'Trees Early Afternoon France',	'1905', None],
    "Hennig_Hostlandskap.png": ['Hennig',	'Otto Hennig',	'Hostlandskap',	'1916', None],
    "Heyerdahl_AtTheWindow.png": ['Heyerdahl',	'Hans Heyerdahl',	'At The Window',	'1881', None],
    "Hiroshige_Seki.png": ['Hiroshige',	'Utagawa Hiroshige',	'Seki',	'1848', None],
    "Hiroshige_Yoshiwara.png": ['Hiroshige',	'Utagawa Hiroshige',	'Yoshiwara',	'1842', None],
    "Hokkei_ThreeCrowsAgainstTheRisingSun.png": ['Hokkei',	'Totoya Hokkei',	'Three Crows Against The Rising Sun',	'1810', None],
    "Hokusai_TheGreatWaveOffKanagawa.png": ['Hokusai',	'Katsushika Hokusai',	'The Great Wave Off Kanagawa',	'1830', None],
    "Homer_Northeaster.png": ['Homer',	'Winslow Homer',	'Northeaster',	'1895', None],
    "Huys_ArmedThreeMasterOnTheOpenSea.png": ['Huys',	'Frans Huys',	'Armed Three Master On The Open Sea',	'1525', None],
    "Ingham_TheFlowerGirl.png": ['Ingham',	'Charles Cromwell Ingham',	'The Flower Girl',	'1846', None],
    "Ingres_FrancoiseDeRimini.png": ['Ingres',	'Jean Auguste Dominique Ingres',	'Francoise De Rimini',	'1814', None],
    "Ingres_JoanOfArcAtTheCoronationOfCharlesVII.png": ['Ingres',	'Jean Auguste Dominique Ingres',	'Joan Of Arc At The Coronation Of Charles VII',	'1854', None],
    "Ingres_PrincesseDeBroglie.png": ['Ingres',	'Jean Auguste Dominique Ingres',	'Princesse De Broglie',	'1851', None],
    "Ingres_RaphaelAndTheFornarina.png": ['Ingres',	'Jean Auguste Dominique Ingres',	'Raphael And The Fornarina',	'1814', None],
    "Ingres_NapoleonOnHisImperialThrone.png": ['Ingres',	'Jean Auguste Dominique Ingres',	'Napoleon on his Imperial Throne',	'1806', None],
    "Ingres_SelfPortraitAtTheAgeOf24.png": ['Ingres',	'Jean Auguste Dominique Ingres',	'Self Portrait At The Age Of 24',	'1804', None],
    "Inness_AutumnOaks.png": ['Inness',	'George Inness',	'Autumn Oaks',	'1878', None],
    "Kensett_LakeGeorge.png": ['Kensett',	'John Frederick Kensett',	'Lake George',	'1869', None],
    "Kensett_SunsetOnTheSea.png": ['Kensett',	'John Frederick Kensett',	'Sunset on the Sea',	'1872', None],
    "Kirchner_Cyclamen.png": ['Kirchner',	'Ernst Ludwig Kirchner',	'Cyclamen',	'1918', None],
    "Klimt_TheKiss.png": ['Klimt',	'Gustav Klimt',	'The Kiss',	'1907', None],
    "Kou_FemaleChanterForJoruriPuppetTheater.png": ['Kou',	'Arai Kou',	'Female Chanter For Joruri Puppet Theater',	'1920', None],
    "Kuindzhi_RedSunsetOnTheDnieper.png": ['Kuindzhi',	'Arkhip Ivanovich Kuindzhi',	'Red Sunset on the Dnieper',	'1905', None],
    "Kuniyoshi_WaterScene.png": ['Kuniyoshi',	'Utagawa Kuniyoshi',	'Water Scene',	'1840', None],
    "LeGray_OakTreeAndRocksForestOfFontainebleau.png": ['Le Gray',	'Gustave Le Gray',	'Oak Tree and Rocks Forest of Fontainebleau',	'1849', None],
    "Leighton_FlamingJune.png": ['Leighton',	'Frederic Leighton',	'Flaming June',	'1895', None],
    "Manet_ABarAtTheFoliesBergere.png": ['Manet',	'Edouard Manet',	'A Bar at the Folies-Bergere',	'1881', None],
    "Manet_YoungLadyIn1866.png": ['Manet',	'Edouard Manet',	'Young Lady In 1866',	'1866', None],
    "Mondrian_CompositionIIInRedBlueAndYellow.png": ['Mondrian',	'Piet Mondrian',	'Composition II in Red, Blue and Yellow',	'1930', None],
    "Mondrian_CompositionNoIV.png": ['Mondrian',	'Piet Mondrian',	'Composition No IV',	'1929', None],
    "Mondrian_TrafalgarSquare1943.png": ['Mondrian',	'Piet Mondrian',	'Trafalgar Square 1943',	'1943', None],
    "Monet_HousesOfParliamentStormySky.png": ['Monet',	'Claude Monet',	'Houses of Parliament Stormy Sky',	'1904', None],
    "Monet_AutumnEffectAtArgenteuil.png": ['Monet',	'Claude Monet',	'Autumn Effect at Argenteuil',	'1873', None],
    "Morse_SusanWalkerMorse.png": ['Morse',	'Samuel F. B. Morse',	'Susan Walker Morse',	'1836', None],
    "Munch_TheScream.png": ['Munch',	'Edvard Munch',	'The Scream',	'1893', None],
    "Post_ViewOfOlindaBrazil.png": ['Post',		'Frans Post',	'View Of Olinda Brazil',	'1662', None],
    "Ranger_HighBridgeNewYork.png": ['Ranger',	'Henry Ward Ranger',	'High Bridge New York',	'1905', None],
    "Redon_EtruscanVaseWithFlowers.png": ['Redon',	'Odilon Redon',	'Etruscan Vase With Flowers',	'1900', None],
    "Rembrandt_PortraitOfGerardDeLairesse.png": ['Rembrandt',	'Rembrandt',	'Portrait Of Gerard De Lairesse',	'1665', None],
    "Rembrandt_SelfPortrait.png": ['Rembrandt',	'Rembrandt',	'Self Portrait',	'1660', None],
    "Rembrandt_TheNightWatch.png": ['Rembrandt',	'Rembrandt',	'The Night Watch',	'1642', None],
    "Rembrandt_PortraitOfAWomanWithGloves.png": ['Rembrandt',	'Rembrandt',	'Portrait of a Woman with Gloves',	'1632', None],
    "Renoir_ChestnutTreeInBloom.png": ['Renoir',	'Pierre-Auguste Renoir',	'Chestnut Tree In Bloom',	'1881', None],
    "Renoir_DanceAtLeMoulinDeLaGalette.png": ['Renoir',	'Pierre-Auguste Renoir',	'Dance At Le Moulin De La Galette',	'1876', None],
    "Romney_MissConstable.png": ['Romney',	'George Romney',	'Miss Constable',	'1787', None],
    "Rossetti_JoanOfArc.png": ['Rossetti',	'Dante Gabriel Rossetti',	'Joan Of Arc',	'1882', None],
    "Rossetti_TheDayDream.png": ['Rossetti',	'Dante Gabriel Rossetti',	'The Day Dream',	'1880', None],
    "Rousseau_BanksOfTheBievre.png": ['Rousseau',	'Henri Rousseau',	'Banks Of The Bievre',	'1908', None],
    "Rousseau_RepastOfTheLion.png": ['Rousseau',	'Henri Rousseau',	'Repast Of The Lion',	'1907', None],
    "Rubens_RubensHisWifeHelenaFourment.png": ['Rubens',	'Peter Paul Rubens',	'Rubens His Wife Helena Fourment',	'1635', None],
    "Rubens_LandscapeWithRainbow.png": ['Rubens',	'Peter Paul Rubens',	'Landscape With Rainbow',	'1630', None],
    "Rubens_OldWomanAndBoyWithCandles.png": ['Rubens',	'Peter Paul Rubens',	'Old Woman And Boy With Candles',	'1616', None],
    "Ryder_AutumnMeadows.png": ['Ryder',	'Albert Pinkham Ryder',	'Autumn Meadows',	'1912', None],
    "Sargent_EllenTerryComeLadyMacbeth.png": ['Sargent',	'John Singer Sargent',	'Ellen Terry Come Lady Macbeth',	'1889', None],
    "Sargent_LadyHelenVincent.png": ['Sargent',	'John Singer Sargent',	'Lady Helen Vincent',	'1904', None],
    "Seurat_StudyForASundayOnLaGrandeJatte.png": ['Seurat',	'Georges Seurat',	'A Sunday On La Grande Jatte',	'1884', None],
    "Sisley_BridgeAtVilleneuveLaGarenne.png": ['Sisley',	'Alfred Sisley',	'Bridge At Villeneuve La Garenne',	'1872', None],
    "Tasker_NationalDefense.png": ['Tasker',	'William Tasker',	'National Defense',	'1943', None],
    "ToulouseLautrec_TheEnglishman.png": ['Toulouse-Lautrec',	'Henri Toulouse-Lautrec',	'The Englishman',	'1892', None],
    "ToulouseLautrec_TheLaundress.png": ['Toulouse-Lautrec',	'Henri Toulouse-Lautrec',	'The Laundress',	'1884', None],
    "Trubner_Landscape.png": ['Trubner',	'Wilhelm Trubner',	'Landscape',	'1910', None],
    "Turner_FlintCastle.png": ['Turner',	'J.M.W. Turner',	'Flint Castle',	'1838', None],
    "Turner_MortlakeTerrace.png": ['Turner',	'J.M.W. Turner',	'Mortlake Terrace',	'1827', None],
    "Turner_RainSteamAndSpeed.png": ['Turner',	'J.M.W. Turner',	'Rain, Steam And Speed',	'1844', None],
    "Turner_RocketsAndBlueLights.png": ['Turner',	'J.M.W. Turner',	'Rockets And Blue Lights',	'1840', None],
    "Turner_TheDeclineOfTheCarthaginianEmpire.png": ['Turner',	'J.M.W. Turner',	'The Decline Of The Carthaginian Empire',	'1817', None],
    "Turner_TheFightingTemeraire.png": ['Turner',	'J.M.W. Turner',	'The Fighting Temeraire',	'1839', None],
    "Turner_TheRainbowOsterspaiAndFilsen.png": ['Turner',	'J.M.W. Turner',	'The Rainbow Osterspai And Filsen',	'1817', None],
    "Turner_TheShipwreck.png": ['Turner',	'J.M.W. Turner',	'The Shipwreck',	'1805', None],
    "Turner_VeniceFromMadonnaDellaSalute.png": ['Turner',	'J.M.W. Turner',	'Venice From Madonna Della Salute',	'1835', None],
    "Turner_Whalers.png": ['Turner',	'J.M.W. Turner',	'Whalers',	'1845', None],
    "Velazquez_JuanDePareja.png": ['Velazquez',	'Diego Velazquez',	'Juan De Pareja',	'1650', None],
    "Velazquez_LasMeninas.png": ['Velazquez',	'Diego Velazquez',	'Las Meninas',	'1656', None],
    "Vermeer_GirlInterruptedAtHerMusic.png": ['Vermeer',	'Johannes Vermeer',	'Girl Interrupted At Her Music',	'1660', None],
    "Vermeer_GirlWithAPearlEarring.png": ['Vermeer',	'Johannes Vermeer',	'Girl With A Pearl Earring',	'1665', None],
    "Vermeer_StudyOfAYoungWoman.png": ['Vermeer',	'Johannes Vermeer',	'Study Of A Young Woman',	'1665', None],
    "Vermeer_TheMusicLesson.png": ['Vermeer',	'Johannes Vermeer',	'The Music Lesson',	'1662', None],
    "Veronese_MarsAndVenusUnitedByLove.png": ['Veronese',	'Paolo Veronese',	'Mars And Venus United By Love',	'1570', None],
    "Whistler_NocturneTheThamesAtBattersea.png": ['Whistler',	'James McNeill Whistler',	'Nocturne: The Thames At Battersea',	'1878', None],
    "Whistler_QuietCanal.png": ['Whistler',	'James McNeill Whistler',	'Quiet Canal',	'1879', None],
    "Whittredge_TheTroutPool.png": ['Whittredge',	'Worthington Whittredge',	'The Trout Pool',	'1870', None],
    "daVinci_LaBelleFerronniere.png": ['da Vinci',	'Leonardo da Vinci',	'La Belle Ferronniere',	'1490', None],
    "daVinci_LadyWithAnErmine.png": ['da Vinci',	'Leonardo da Vinci',	'Lady With An Ermine',	'1490', None],
    "daVinci_MonaLisa.png": ['da Vinci',	'Leonardo da Vinci',	'Mona Lisa',	'1503', None],
    "daVinci_StJohnTheBaptist.png": ['da Vinci',	'Leonardo da Vinci',	'St John The Baptist',	'1513', None],
    "deHooch_LeisureTimeInAnElegantSetting.png": ['de Hooch',	'Pieter de Hooch',	'Leisure Time In An Elegant Setting',	'1663', None],
    "vanGogh_CafeTerraceAtNight.png": ['van Gogh',	'Vincent van Gogh',	'Cafe Terrace At Night',	'1888', None],
    "vanGogh_Irises.png": ['van Gogh',	'Vincent van Gogh',	'Irises',	'1890', None],
    "vanGogh_OliveTrees.png": ['van Gogh',	'Vincent van Gogh',	'Olive Trees',	'1889', None],
    "vanGogh_Roses.png": ['van Gogh',	'Vincent van Gogh',	'Roses',	'1890', None],
    "vanGogh_SelfPortraitWithStrawHat.png": ['van Gogh',	'Vincent van Gogh',	'Self Portrait With Straw Hat',	'1887', None],
    "vanGogh_StarryNight.png": ['van Gogh',	'Vincent van Gogh',	'Starry Night',	'1889', None],
    "vanGogh_StarryNightOverTheRhone.png": ['van Gogh',	'Vincent van Gogh',	'Starry Night Over The Rhone',	'1888', None],
    "vanGogh_TheFloweringOrchard.png": ['van Gogh',	'Vincent van Gogh',	'The Flowering Orchard',	'1888', None],
    "vanGogh_WheatFieldWithCypresses.png": ['van Gogh',	'Vincent van Gogh',	'Wheat Field With Cypresses',	'1889', None],
    "vanGogh_SelfPortraitWithABandagedEar.png": ['van Gogh',	'Vincent van Gogh',	'Self Portrait With A Bandaged Ear',	'1889', None],
    "vanGogh_Sunflowers.png": ['van Gogh',	'Vincent van Gogh',	'Sunflowers',	'1888', None],
    "c19_Hokkei_RomanticScene.png": ['Hokkei',	'Totoya Hokkei',	"Romantic Scene",	'1840', "Edo period (1615–1868)"],
    "c19_Hokkei_LobsterOnPieceOfCharcoal.png": ['Hokkei',	'Totoya Hokkei',	"Lobster On Piece Of Charcoal",	'1840', "Edo period (1615–1868)"]
}




if __name__ == "__main__":
    progname = string.split(sys.argv[0], os.pathsep)[-1]
    print "%s (V %s)" % (progname, __VERSION__)
    print
    print "%s pictures known about" % len(art_info)
